export enum AuditAction {
  CREATE = 'CREATE',
  UPLOAD = 'UPLOAD',
  DOWNLOAD = 'DOWNLOAD',
  DELETE = 'DELETE',
  RENAME = 'RENAME',
  MOVE = 'MOVE',
  RESTORE = 'RESTORE',
  SHARE = 'SHARE',
  UPDATE_VISIBILITY = 'UPDATE_VISIBILITY',
  UPDATE = 'UPDATE',
}
