version: 2

postal:
  web_hostname: mail.bemftunesa.org
  web_protocol: https
  smtp_hostname: mail.bemftunesa.org

main_db:
  host: postal-db
  username: root
  password: postal_root_2026
  database: postal

message_db:
  host: postal-db
  username: root
  password: postal_root_2026
  prefix: postal

smtp_server:
  default_bind_address: "::"

dns:
  mx_records:
    - mail.bemftunesa.org
  spf_include: bemftunesa.org
  return_path_domain: mail.bemftunesa.org
  route_domain: mail.bemftunesa.org
  track_domain: mail.bemftunesa.org

smtp:
  host: postal-db
  port: 25
  username:
  password:
  from_name: BEM FT UNESA 2026
  from_address: noreply@bemftunesa.org

rails:
  secret_key: CHANGE_ME_ON_FIRST_BOOT
