depends_on: [lint]
steps:
  - name: push-api
    image: woodpeckerci/plugin-docker-buildx
    privileged: true
    settings:
      repo: ghcr.io/dihanio/bemftunesa2026-api
      tags: [latest, ${CI_COMMIT_SHA:0:8}]
      registry: ghcr.io
      username: dihanio
      password:
        from_secret: github_token
      dockerfile: Dockerfile.backend
      target: runner
      platforms: [linux/amd64]
      cache_from: ghcr.io/dihanio/bemftunesa2026-api:buildcache
      cache_to: type=registry,ref=ghcr.io/dihanio/bemftunesa2026-api:buildcache,mode=min
    when:
      - event: [push, tag]
        branch: main
        path:
          include: [backend/**, packages/**, package.json, package-lock.json, turbo.json, Dockerfile.backend]
