depends_on: [lint]
steps:
  - name: push-pkkmb-web
    image: woodpeckerci/plugin-docker-buildx
    privileged: true
    settings:
      repo: ghcr.io/dihanio/bemftunesa2026-pkkmb_web
      tags:
        - latest
        - ${CI_COMMIT_SHA:0:8}
      registry: ghcr.io
      username: dihanio
      password:
        from_secret: github_token
      dockerfile: Dockerfile.frontend
      target: runner
      platforms: [linux/amd64]
      build_args:
        APP_NAME: pkkmb
        NEXT_PUBLIC_API_URL: https://api.bemftunesa.org/api/v1
        NEXT_PUBLIC_PUBLIC_URL: https://bemftunesa.org
        NEXT_PUBLIC_IMS_URL: https://ims.bemftunesa.org
        NEXT_PUBLIC_GOOGLE_CLIENT_ID: dummy-client-id
      cache_from: ghcr.io/dihanio/bemftunesa2026-pkkmb_web:buildcache
      cache_to: type=registry,ref=ghcr.io/dihanio/bemftunesa2026-pkkmb_web:buildcache,mode=min
    when:
      - event: [push, tag]
        branch: main
        path:
          include: [pkkmb/**, packages/**, package.json, package-lock.json, turbo.json, Dockerfile.frontend]
